# Generated by Django 4.2.4 on 2024-03-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240324_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
